---
AWSTemplateFormatVersion: '2010-09-09'
Description: Customer Sentiment S3 Configuration

Parameters:
  Region:
    Type: String
    AllowedValues: [ us-east-1, us-west-1, eu-west-1 ]

Resources:
  ConfigBucket:
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
#      BucketName: !Ref "BucketName"
      AccessControl: BucketOwnerFullControl
      Tags:
        -
          Key: Name
          Value: happymeter-s3-config

Outputs:
  BucketId:
    Value: !Ref "ConfigBucket"
    Export:
      Name: !Sub "${AWS::StackName}-BucketId"

      