---
AWSTemplateFormatVersion: '2010-09-09'
Description: Customer Sentiment Lambda Task

Parameters:
  ConfigPkg:
    Type: String
    Default: happymeter.zip

  ConfigStack:
    Type: String
    
  Region:
    Type: String
    AllowedValues: [ us-east-1, us-west-1, eu-west-1 ]

  RoleStack:
    Type: String
  
Resources:
  Lambda1:
    DeletionPolicy: Delete
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub "${ConfigStack}-BucketId"
        S3Key: !Ref "ConfigPkg"
      Description: 'Extract Emotion data using Rekognition'
      Handler: index.handler
      Role:
          Fn::ImportValue: !Sub "${RoleStack}-PolicyArn"
      Runtime: python2.7
      Tags:
        -
          Key: Name
          Value: happymeter-lambda-detect-faces
      Timeout: 5

  LambdaPermission:
    DeletionPolicy: Delete
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt [ Lambda1, Arn ]
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'

Outputs:
  LambdaId:
    Value: !Ref "Lambda1"
    Export:
      Name: !Sub "${AWS::StackName}-Lambda"

  LambdaArn:
    Value: !GetAtt [ Lambda1, Arn ]
    Export:
      Name: !Sub "${AWS::StackName}-LambdaArn"
    